import { ChildrenNode } from "@/types"
import "./globals.scss"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Footer, Navbar } from "@/components/Base"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: ChildrenNode) {
  return (
    <html lang="en" dir="ltr">
      <body className={inter.className}>
        <Navbar />
        <main id="skip-to-main-content">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
