import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyFursona</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div id={styles.wrapper}>
          <div id={styles["search-box-wrapper"]}>
            <strong className={styles.logo}>
              MyFursona
            </strong>
            <input type="text" placeholder='Search for any fursonas...' id={styles["search-box"]} />
          </div>
          <div id={styles["user-actions"]}>
            {/* SVG logos here for logged in users */}

            {/* Display somemthing here for logged out users */}
            <button>Login</button>
          </div>
        </div>
      </header>

      <main>
        <div id={styles["fursona-main-showcase"]}>
          <section>
            <h2>🔥 Popular Fursonas</h2>
            <div className="fursona-gallery-grid">
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
            </div>
          </section>
          <section>
            <h2>✨ New Fursonas</h2>
            <div className="fursona-gallery-grid">
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
              <div className="fursona-gallery-item"></div>
            </div>
          </section>
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
