import "@myfursona/biro-ui/styles/globals.scss"

import type { Metadata } from "next"
import { Inter, Open_Sans } from "next/font/google"

const inter = Inter({
  subsets: ["latin", "cyrillic-ext"],
  preload: true,
  variable: "--font-inter"
})

const open_sans = Open_Sans({
  subsets: ["latin", "cyrillic-ext"],
  preload: true,
  variable: "--font-open-sans"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${open_sans.variable}`}>
      <body className="bg-100 text-700">{children}</body>
    </html>
  )
}
