version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
      time: "00:00"
    open-pull-requests-limit: 3
    assignees:
      - VulpoTheDev
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
