name: Format / Lint / Dependency Checks
on: [push]

jobs:
  check-code-format:
    name: "Check code format and lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn

      - name: "Formatting: Prettier"
        id: prettier
        run: yarn prettier --check .
        continue-on-error: true

      - name: "Formatting: ESLint"
        id: eslint
        run: yarn eslint .
        continue-on-error: true

      - name: "Check outcomes"
        if: always()
        run: |
          if [[ "${{ steps.prettier.outcome }}" != "success" || "${{ steps.eslint.outcome }}" != "success" ]]; then
            echo "Formatting checks failed; make sure to format and lint your code accordingly!"
            exit 1
          fi

  knip-deps:
    name: "Unused code & dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn

      - name: "Dependencies: Knip"
        run: yarn knip
