name: Linting and TypeScript Check

on:
  push:
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"

jobs:
  linting-typescript-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use yarn cache keyed by hashed yarn.lock
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting Check
        run: yarn lint

      - name: TypeScript Check
        run: yarn typescript:check
