name: Codebase format and lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm i -g yarn
      - run: yarn install --no-lockfile
      - name: Run Prettier
        run: yarn prettier --check .
      - name: Run lints
        run: yarn turbo lint